// Code generated by MockGen. DO NOT EDIT.
// Source: ./parser.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	rpc "github.com/make-software/casper-go-sdk/rpc"
	types "github.com/make-software/casper-go-sdk/types"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetAccountBalance mocks base method.
func (m *MockClient) GetAccountBalance(ctx context.Context, stateRootHash, purseURef string) (rpc.StateGetBalanceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountBalance", ctx, stateRootHash, purseURef)
	ret0, _ := ret[0].(rpc.StateGetBalanceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalance indicates an expected call of GetAccountBalance.
func (mr *MockClientMockRecorder) GetAccountBalance(ctx, stateRootHash, purseURef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalance", reflect.TypeOf((*MockClient)(nil).GetAccountBalance), ctx, stateRootHash, purseURef)
}

// GetAuctionInfoByHash mocks base method.
func (m *MockClient) GetAuctionInfoByHash(ctx context.Context, blockHash string) (rpc.StateGetAuctionInfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuctionInfoByHash", ctx, blockHash)
	ret0, _ := ret[0].(rpc.StateGetAuctionInfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuctionInfoByHash indicates an expected call of GetAuctionInfoByHash.
func (mr *MockClientMockRecorder) GetAuctionInfoByHash(ctx, blockHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuctionInfoByHash", reflect.TypeOf((*MockClient)(nil).GetAuctionInfoByHash), ctx, blockHash)
}

// GetAuctionInfoByHeight mocks base method.
func (m *MockClient) GetAuctionInfoByHeight(ctx context.Context, height uint64) (rpc.StateGetAuctionInfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuctionInfoByHeight", ctx, height)
	ret0, _ := ret[0].(rpc.StateGetAuctionInfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuctionInfoByHeight indicates an expected call of GetAuctionInfoByHeight.
func (mr *MockClientMockRecorder) GetAuctionInfoByHeight(ctx, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuctionInfoByHeight", reflect.TypeOf((*MockClient)(nil).GetAuctionInfoByHeight), ctx, height)
}

// GetAuctionInfoLatest mocks base method.
func (m *MockClient) GetAuctionInfoLatest(ctx context.Context) (rpc.StateGetAuctionInfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuctionInfoLatest", ctx)
	ret0, _ := ret[0].(rpc.StateGetAuctionInfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuctionInfoLatest indicates an expected call of GetAuctionInfoLatest.
func (mr *MockClientMockRecorder) GetAuctionInfoLatest(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuctionInfoLatest", reflect.TypeOf((*MockClient)(nil).GetAuctionInfoLatest), ctx)
}

// GetBlockByHash mocks base method.
func (m *MockClient) GetBlockByHash(ctx context.Context, hash string) (rpc.ChainGetBlockResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByHash", ctx, hash)
	ret0, _ := ret[0].(rpc.ChainGetBlockResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByHash indicates an expected call of GetBlockByHash.
func (mr *MockClientMockRecorder) GetBlockByHash(ctx, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByHash", reflect.TypeOf((*MockClient)(nil).GetBlockByHash), ctx, hash)
}

// GetBlockByHeight mocks base method.
func (m *MockClient) GetBlockByHeight(ctx context.Context, height uint64) (rpc.ChainGetBlockResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByHeight", ctx, height)
	ret0, _ := ret[0].(rpc.ChainGetBlockResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByHeight indicates an expected call of GetBlockByHeight.
func (mr *MockClientMockRecorder) GetBlockByHeight(ctx, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByHeight", reflect.TypeOf((*MockClient)(nil).GetBlockByHeight), ctx, height)
}

// GetBlockLatest mocks base method.
func (m *MockClient) GetBlockLatest(ctx context.Context) (rpc.ChainGetBlockResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockLatest", ctx)
	ret0, _ := ret[0].(rpc.ChainGetBlockResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockLatest indicates an expected call of GetBlockLatest.
func (mr *MockClientMockRecorder) GetBlockLatest(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockLatest", reflect.TypeOf((*MockClient)(nil).GetBlockLatest), ctx)
}

// GetBlockTransfersByHash mocks base method.
func (m *MockClient) GetBlockTransfersByHash(ctx context.Context, blockHash string) (rpc.ChainGetBlockTransfersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockTransfersByHash", ctx, blockHash)
	ret0, _ := ret[0].(rpc.ChainGetBlockTransfersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockTransfersByHash indicates an expected call of GetBlockTransfersByHash.
func (mr *MockClientMockRecorder) GetBlockTransfersByHash(ctx, blockHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockTransfersByHash", reflect.TypeOf((*MockClient)(nil).GetBlockTransfersByHash), ctx, blockHash)
}

// GetBlockTransfersByHeight mocks base method.
func (m *MockClient) GetBlockTransfersByHeight(ctx context.Context, height uint64) (rpc.ChainGetBlockTransfersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockTransfersByHeight", ctx, height)
	ret0, _ := ret[0].(rpc.ChainGetBlockTransfersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockTransfersByHeight indicates an expected call of GetBlockTransfersByHeight.
func (mr *MockClientMockRecorder) GetBlockTransfersByHeight(ctx, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockTransfersByHeight", reflect.TypeOf((*MockClient)(nil).GetBlockTransfersByHeight), ctx, height)
}

// GetBlockTransfersLatest mocks base method.
func (m *MockClient) GetBlockTransfersLatest(ctx context.Context) (rpc.ChainGetBlockTransfersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockTransfersLatest", ctx)
	ret0, _ := ret[0].(rpc.ChainGetBlockTransfersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockTransfersLatest indicates an expected call of GetBlockTransfersLatest.
func (mr *MockClientMockRecorder) GetBlockTransfersLatest(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockTransfersLatest", reflect.TypeOf((*MockClient)(nil).GetBlockTransfersLatest), ctx)
}

// GetDeploy mocks base method.
func (m *MockClient) GetDeploy(ctx context.Context, hash string) (rpc.InfoGetDeployResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeploy", ctx, hash)
	ret0, _ := ret[0].(rpc.InfoGetDeployResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeploy indicates an expected call of GetDeploy.
func (mr *MockClientMockRecorder) GetDeploy(ctx, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeploy", reflect.TypeOf((*MockClient)(nil).GetDeploy), ctx, hash)
}

// GetDictionaryItem mocks base method.
func (m *MockClient) GetDictionaryItem(ctx context.Context, stateRootHash, uref, key string) (rpc.StateGetItemResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDictionaryItem", ctx, stateRootHash, uref, key)
	ret0, _ := ret[0].(rpc.StateGetItemResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDictionaryItem indicates an expected call of GetDictionaryItem.
func (mr *MockClientMockRecorder) GetDictionaryItem(ctx, stateRootHash, uref, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDictionaryItem", reflect.TypeOf((*MockClient)(nil).GetDictionaryItem), ctx, stateRootHash, uref, key)
}

// GetEraInfoByBlockHash mocks base method.
func (m *MockClient) GetEraInfoByBlockHash(ctx context.Context, hash string) (rpc.ChainGetEraInfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEraInfoByBlockHash", ctx, hash)
	ret0, _ := ret[0].(rpc.ChainGetEraInfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEraInfoByBlockHash indicates an expected call of GetEraInfoByBlockHash.
func (mr *MockClientMockRecorder) GetEraInfoByBlockHash(ctx, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEraInfoByBlockHash", reflect.TypeOf((*MockClient)(nil).GetEraInfoByBlockHash), ctx, hash)
}

// GetEraInfoByBlockHeight mocks base method.
func (m *MockClient) GetEraInfoByBlockHeight(ctx context.Context, height uint64) (rpc.ChainGetEraInfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEraInfoByBlockHeight", ctx, height)
	ret0, _ := ret[0].(rpc.ChainGetEraInfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEraInfoByBlockHeight indicates an expected call of GetEraInfoByBlockHeight.
func (mr *MockClientMockRecorder) GetEraInfoByBlockHeight(ctx, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEraInfoByBlockHeight", reflect.TypeOf((*MockClient)(nil).GetEraInfoByBlockHeight), ctx, height)
}

// GetEraInfoLatest mocks base method.
func (m *MockClient) GetEraInfoLatest(ctx context.Context) (rpc.ChainGetEraInfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEraInfoLatest", ctx)
	ret0, _ := ret[0].(rpc.ChainGetEraInfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEraInfoLatest indicates an expected call of GetEraInfoLatest.
func (mr *MockClientMockRecorder) GetEraInfoLatest(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEraInfoLatest", reflect.TypeOf((*MockClient)(nil).GetEraInfoLatest), ctx)
}

// GetPeers mocks base method.
func (m *MockClient) GetPeers(ctx context.Context) (rpc.InfoGetPeerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeers", ctx)
	ret0, _ := ret[0].(rpc.InfoGetPeerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeers indicates an expected call of GetPeers.
func (mr *MockClientMockRecorder) GetPeers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeers", reflect.TypeOf((*MockClient)(nil).GetPeers), ctx)
}

// GetStateItem mocks base method.
func (m *MockClient) GetStateItem(ctx context.Context, stateRootHash, key string, path []string) (rpc.StateGetItemResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStateItem", ctx, stateRootHash, key, path)
	ret0, _ := ret[0].(rpc.StateGetItemResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStateItem indicates an expected call of GetStateItem.
func (mr *MockClientMockRecorder) GetStateItem(ctx, stateRootHash, key, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateItem", reflect.TypeOf((*MockClient)(nil).GetStateItem), ctx, stateRootHash, key, path)
}

// GetStateRootHashByHash mocks base method.
func (m *MockClient) GetStateRootHashByHash(ctx context.Context, stateRootHash string) (rpc.ChainGetStateRootHashResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStateRootHashByHash", ctx, stateRootHash)
	ret0, _ := ret[0].(rpc.ChainGetStateRootHashResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStateRootHashByHash indicates an expected call of GetStateRootHashByHash.
func (mr *MockClientMockRecorder) GetStateRootHashByHash(ctx, stateRootHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateRootHashByHash", reflect.TypeOf((*MockClient)(nil).GetStateRootHashByHash), ctx, stateRootHash)
}

// GetStateRootHashByHeight mocks base method.
func (m *MockClient) GetStateRootHashByHeight(ctx context.Context, height uint64) (rpc.ChainGetStateRootHashResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStateRootHashByHeight", ctx, height)
	ret0, _ := ret[0].(rpc.ChainGetStateRootHashResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStateRootHashByHeight indicates an expected call of GetStateRootHashByHeight.
func (mr *MockClientMockRecorder) GetStateRootHashByHeight(ctx, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateRootHashByHeight", reflect.TypeOf((*MockClient)(nil).GetStateRootHashByHeight), ctx, height)
}

// GetStateRootHashLatest mocks base method.
func (m *MockClient) GetStateRootHashLatest(ctx context.Context) (rpc.ChainGetStateRootHashResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStateRootHashLatest", ctx)
	ret0, _ := ret[0].(rpc.ChainGetStateRootHashResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStateRootHashLatest indicates an expected call of GetStateRootHashLatest.
func (mr *MockClientMockRecorder) GetStateRootHashLatest(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStateRootHashLatest", reflect.TypeOf((*MockClient)(nil).GetStateRootHashLatest), ctx)
}

// GetStatus mocks base method.
func (m *MockClient) GetStatus(ctx context.Context) (rpc.InfoGetStatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx)
	ret0, _ := ret[0].(rpc.InfoGetStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockClientMockRecorder) GetStatus(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockClient)(nil).GetStatus), ctx)
}

// PutDeploy mocks base method.
func (m *MockClient) PutDeploy(ctx context.Context, deploy types.Deploy) (rpc.PutDeployResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutDeploy", ctx, deploy)
	ret0, _ := ret[0].(rpc.PutDeployResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutDeploy indicates an expected call of PutDeploy.
func (mr *MockClientMockRecorder) PutDeploy(ctx, deploy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutDeploy", reflect.TypeOf((*MockClient)(nil).PutDeploy), ctx, deploy)
}
